<a href="https://colab.research.google.com/github/dataqueenpend/DS_From_Zero_To_Hero/blob/gh-pages/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# NumPy - Basic info

##### What is NumPy?

Numerical Python library - casually going by the name of **NumPy** - is a core Python package for scientific computing. It adds to the Python possibility to use **multi-dimensional arrays** and perform more advanced mathematical operations. 

NumPy is build with C, wrapped with a Python API. And precisely this C base is responsible for NumPy **high-performance and speed**.

##### Why use NumPy?

NumPy is **fast**, **useful** and allows the user to perform many different Data Science tasks with less amount of code. Furthermore, NumPy is an underlying library for other popular Python packages such as:
* Matplotlib
* Pandas
* Scikit-learn

and those above are a must in Machine Learning, Deep Learning and Data Science. To use other tools based on NumPy is good to know this library first - it is easier to understand them, if the user has a comprehension of the fundamentals behind them. 

##### NumPy Arrays

Main object of NumPy is multi-dimensional table object called **ndarray**. Why 'nd'? It reffers to **n-number of dimensions**, which means that one can create with NumPy simple 1d-arrays as well as 2d-arrays, 3d-arrays and whatever number of dimensional array one want. 

All elements store in the Array are the same type. If upon a creation of array we pass to it **elements of different type**, they **will be unified to one** the most suitable. 

In [ ]:
import numpy as np
l = [1,2,'s', 1 and 1]
l_c_a = np.array(l)
print(l_c_a)
print(type(l_c_a))
print(type(l_c_a[0]))
print(type(l_c_a[2]))
print(type(l_c_a[3]))

['1' '2' 's' '1']
<class 'numpy.ndarray'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>


In above example we have 3 types of data:
* integer
* string
* bool

The most suitable conversion for NumPy was to stored all the elements of the previous list in one type array consisting only string type elements ```numpy.str_```.

This feature of the NumPy arrays is really helpful, especially while working with corrupted data sets. 

---

But let's take a one step back. Straight to the beginning...

#### Installing and importing NumPy


If you want to start using NumPy library, the first thing you need to do is to install and import it. 

If you are **using your operating system for coding** you need to install NumPy before the import. 


In [ ]:
pip install numpy

or 

In [ ]:
conda install numpy

**Don't want to use your own machine?** No problem! There are multiple tools (like [Google Collaboratory](https://colab.research.google.com/notebooks/welcome.ipynb?hl=pl)) for Python users, in which you don't need to trouble yourself with installing every single Python library or the updates. And before using NumPy code all you need to do is just import NumPy.  

In [5]:
import numpy as np

We are importing NumPy as *np* in order to short the commands - means for easier and quicker use. It's a commonly you short, and you will see it almost everytime when someone is using NumPy. 

## Creating an Array

Ready to **create your first NumPy Array**? Let's do it! 

We've already installed and imported NumPy library, so we can start building some arrays. To do so, we use ```np.array``` function, pass to it some numerical data and store it all in a new variable.

In [6]:
new_array = np.array([1,2,3,4,5])

It is done? 

Let's check the data type of this object. 

In [7]:
type(new_array)

numpy.ndarray

Great! 

**We've just created an numpy array!** But what about those famous **n**darray. Let's create some multi-dimensional array. 

In [9]:
new_2d_array = np.array([[1.0, 2.0, 3.0], [4.0, 5.0, 6.0]]) # Let's use some floats to do this!
type(new_2d_array) # Checking the type of object we have

numpy.ndarray

It is as easy, as creating 1d array! But **take a closer look at this one**... Did you see double square brackets? Remember that when we create multi-dimensional array, we need to store every 'dimension' in dedicated square brackets! 

Let's take a look on our freshly created 2d array.

In [10]:
print(new_2d_array)

[[1. 2. 3.]
 [4. 5. 6.]]


Beautiful matrix! 

Now we know how to create single and multi-dimensional arrays. What will you say for a little NumPy vs. List exepriment? 

Are ready for more NumPy? 

## NumPy Arrays vs. Lists

Why use NumPy Arrays instead of Python lists? There are multiple reasons to do that. We've covered a bit above. Arrays are faster, homogenous (store only one type of data), and they give us enourmous ways to store and manipulate numerical data inside them. 

##### Let's look at some example, shall we? 

Say... We want to **add values stored in the first list, to the values store in the second list. Each by each**. Can we do it with a list?

In [1]:
list1 = [1,2,3,4,5]
list2 = [2,3,4,5,6]


We've created 2 lists. Let's add them!

In [3]:
completelist = list1 + list2
print(completelist)

[1, 2, 3, 4, 5, 2, 3, 4, 5, 6]


Did the result of adding lists together was as we desired? 
Unfortunatelly not. By adding two lists we've created a new list storing all the elements of two previous lists. 

**Can we sum the elements of** ```list1``` **to elements of** ```list2```**?** 
Yes, we can do that. And it would look like that:

In [4]:
result = [] # Creating an empty list
for a,b in zip(list1, list2): # Itterating with an iterator a,b through zipped list1 and list2
  result.append(a + b)# Appending sum of elements from the lists to the new list
result


[3, 5, 7, 9, 11]

**Looks rather complicated for such a basic operation, isn't it?** Or even if it is not (for you), with arrays it can be done quicker and simpler. 

Let's take a look. 

* We'll transform our lists into np.arrays.

In [12]:
np_array1 = np.array(list1)
np_array2 = np.array(list2)

type(np_array1)

numpy.ndarray

* And add them together. How it will go?

In [14]:
print([np_array1, np_array2]) # Printing what our arrays contains before summing up the ellements of the lists
np_array1 + np_array2 

[array([1, 2, 3, 4, 5]), array([2, 3, 4, 5, 6])]


array([ 3,  5,  7,  9, 11])

Great! Finally we have the **sum of the elements** from the first array and the corresponding values from the second array. 

We can perform this way also different types of basic operations.

In [15]:
np_array1 * np_array2 # Multiplication

array([ 2,  6, 12, 20, 30])

In [16]:
np_array1 / np_array2 # Division

array([0.5       , 0.66666667, 0.75      , 0.8       , 0.83333333])

In [17]:
np_array1 - np_array2 # Subtraction

array([-1, -1, -1, -1, -1])

## Basic operations in Arrays